name: firelang
description: "Automate multi-language support for Firebase Remote Config in Flutter"
version: 1.0.0
homepage: https://github.com/alltruevalue/firelang
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^5.0.0