name: firelang
description: "Automates Firebase Remote Config multi-language support in Flutter apps."
repository: https://github.com/alltruevalue/firelang
issue_tracker: https://github.com/alltruevalue/firelang/issues
license: MIT
topics:
  - firebase
  - flutter
  - localization
  - remote-config
version: 1.0.1
homepage: https://github.com/alltruevalue/firelang
environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^5.0.0
  firebase_remote_config: ^5.4.1